# Generated by Django 4.1.4 on 2022-12-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='allotted_time',
            field=models.IntegerField(),
        ),
    ]
