# Generated by Django 4.1.4 on 2022-12-30 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_allotted_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='subcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='auctions.comments'),
        ),
    ]
