# Generated by Django 4.1.4 on 2023-01-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
